### Get all accounts

GET http://localhost:9000/accounts HTTP/1.1
Accept: application/json

### Get An Account

GET http://localhost:9000/accounts/01cea490-7f25-4a20-8756-c038a23cd5ba HTTP/1.1
Accept: application/json


### Add An Account

POST http://localhost:9000/accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "Joe Schmidt"
}