### Get all accounts

GET http://localhost:9000/accounts HTTP/1.1
Accept: application/json

### Get An Account

GET http://localhost:9000/accounts/85f97f0d-37b8-4875-8619-b5a8ff7a0bc2 HTTP/1.1
Accept: application/json


### Add An Account

POST http://localhost:9000/accounts HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "Temp"
}